CREATE DATABASE migrar;

CREATE TABLE ANTIGA(
ID_USER INT AUTO_INCREMENT PRIMARY KEY,
CONTATO VARCHAR(60),
EMAIL VARCHAR(40) UNIQUE,
ENDERECO VARCHAR(70),
DATA_CADASTRO DATE
);

CREATE TABLE NOVA(
ID_USER INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60),
TELEFONE VARCHAR(16),
EMAIL VARCHAR(40) UNIQUE,
ENDERECO VARCHAR(70),
DATA_CADASTRO DATE
);

INSERT INTO ANTIGA VALUES(NULL, 'João Silva, (11) 98765-4321', 'joao@email.com', 'Rua A, 100 - SP', '2023-12-01'),
(NULL, 'Maria Souza, (21) 99876-5432', 'maria@email.com', 'Av. B, 200 - RJ', '2024-01-15'),
(NULL, 'Carlos Lima, (31) 98765-1111', 'carlos@email.com', 'Rua C, 300 - MG', '2023-11-20');

INSERT INTO NOVA (ID_USER, NOME, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO)
SELECT ID_USER, SUBSTRING_INDEX(CONTATO, ',', 1) AS NOME,
TRIM(SUBSTRING_INDEX(CONTATO, ',', -1)) AS TELEFONE,
EMAIL, ENDERECO, DATA_CADASTRO FROM ANTIGA.

CREATE TABLE COMPRAS_ANTIGA(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(40),
PRODUTOS VARCHAR(100),
DATA_COMPRA DATE
);

CREATE TABLE COMPRAS_NOVA(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(40),
PRODUTO VARCHAR(100),
DATA_COMPRA DATE
);

INSERT INTO COMPRAS_ANTIGA VALUES (NULL, 'João Silva', 'TV; Notebook; Celular', '2024-02-10'),
(NULL, 'Maria Souza', 'Geladeira; Fogão', '2024-02-12'),
(NULL, 'Carlos Lima', 'TV; Home Theater', '2024-02-15');





