/*JOIN de duas tabelas*/
SELECT C.ID_CLIENTE, C.NOME, C.EMAIL, C.SEXO, E.CIDADE, E.UF
FROM CLIENTE C 
INNER JOIN ENDERECO E
ON C.ID_CLIENTE = E.ID_CLIENTE;


/*JOIN de 3 tabelas trazendo o ID_CLIENTE*/
SELECT C.ID_CLIENTE, NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO
FROM CLIENTE C
JOIN ENDERECO E ON C.ID_CLIENTE = E.ID_CLIENTE 
JOIN TELEFONE T ON C.ID_CLIENTE = T.ID_CLIENTE;

SELECT LOTE.CODI_PSV, TB_K3.CODIGO_PRODUTO, LOTE.LOTE_LOT, TB_K3.LOTE
FROM LOTE LOTE
JOIN TB_SALDO_LOTE_K3 TB_K3 ON LOTE.CODI_PSV = TB_K3.CODIGO_PRODUTO
LEFT JOIN LOTE ON LOTE.LOTE_LOT = TB_K3.LOTE;